import { Rubik } from 'next/font/google';
import './globals.css';
import Header from './component/Header';
import Wrapper from './component/Wrapper';

import './assets/css/tailwind.css';
import './assets/scss/tailwind.scss';

import './assets/scss/icons.scss';
import Footer from './component/Footer';
import Switcher from './component/Switcher';
import Console from './component/Console';

const rubic = Rubik({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    display: 'swap',
    variable: '--font-rubic',
});

export const metadata = {
    title: 'Upwind - Next Js Landing Page Template',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    console.log(
  "%cHi developers, if you want to contribute to this project visit %chttps://github.com/KoaCook",
  "color: #3b82f6; font-size: 16px; font-weight: bold;",
  "color: #16a34a; font-size: 16px; text-decoration: underline;"
);
    
    return (
        <html lang="en" dir="LTR" className="scroll-smooth">
            <body className={`${rubic.variable}`}>
                <Wrapper>
                    <Header />
                    {children}

                    <Footer />
                    <Switcher />
                    <Console />
                </Wrapper>
            </body>
        </html>
    );
}
